name: Pylint

on:
  push:
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pylint-exit
        pip install -r requirements.txt
    - name: Run Pylint on code
      run: |
        pylint --rc-file=pylintrc --disable=import-error $(git ls-files '*.py') || pylint-exit --error-fail $?
        if [ $? -ne 0 ]; then
          exit 1
        fi
